spring:
  datasource:
    url: "jdbc:h2:tcp://localhost/~/study/db/posting/posting;MODE=MYSQL;"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          show_sql: true
          dialect: org.hibernate.dialect.H2Dialect
      open-in-view: false
  h2:
      console:
        enabled: true
        path: /h2-console